---
# Source: app-chart/charts/base-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-chart-my-app
  labels:
    helm.sh/chart: base-chart-0.2.0
    app.kubernetes.io/name: my-app
    app.kubernetes.io/instance: app-chart
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: app-chart/charts/base-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-chart-my-app
  labels:
    helm.sh/chart: base-chart-0.2.0
    app.kubernetes.io/name: my-app
    app.kubernetes.io/instance: app-chart
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/instance: app-chart
---
# Source: app-chart/charts/base-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-chart-my-app
  labels:
    helm.sh/chart: base-chart-0.2.0
    app.kubernetes.io/name: my-app
    app.kubernetes.io/instance: app-chart
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type:RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: my-app
      app.kubernetes.io/instance: app-chart
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-app
        app.kubernetes.io/instance: app-chart
    spec:
      serviceAccountName: app-chart-my-app
      securityContext:
        {}
      containers:
        - name: base-chart
          securityContext:
            {}
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
